### PR TITLE
fix(mavlink): gate UAVCAN param bridge on observed camera heartbeat

### LINKED ISSUE #27180: DroneCAN param bridge silently drops requests to node IDs 100–105 (MAV_COMP_ID_CAMERA range) — regression from #25651
## Summary

On `release/1.16` (v1.16.1), every `v1.17` pre-release, and current `main`,
`PARAM_REQUEST_LIST`, `PARAM_SET`, and `PARAM_REQUEST_READ` aimed at a MAVLink
`target_component` in 100–105 are silently dropped by the UAVCAN parameter
bridge handler. Because that handler maps `target_component` 1:1 onto the
UAVCAN `node_id`, this also means **DroneCAN peripherals (e.g. ESCs) at CAN
node IDs 100–105 are unreachable via MAVLink parameters**.

Field symptom: QGroundControl's parameter download hangs / times out whenever a
DroneCAN ESC is powered at a node ID in 100–105. Reassigning the node ID to
anything outside that range resolves it.

## Reproduction

- PX4 v1.16.1, or any v1.17 pre-release (α1 … rc2), or `main` at the time of
  writing.
- A DroneCAN peripheral (ESC works well for repro) at node ID ∈ {100, 101,
  102, 103, 104, 105}, powered and emitting NodeStatus so QGC sees the
  component.
- In QGC: open Vehicle Setup → param download to that component stalls /
  times out.

Node IDs outside 100–105 — verified 26–29, 99, 106, 107–113, 120, 126 — are
unaffected.

## Cause

PR #25651 added this guard at three sites in
`src/modules/mavlink/mavlink_parameters.cpp` (lines 82, 141, 219 on `main`):

```cpp
&& !(target_component >= MAV_COMP_ID_CAMERA && target_component <= MAV_COMP_ID_CAMERA6)
```

Per MAVLink minimal.xml, `MAV_COMP_ID_CAMERA` = 100 and
`MAV_COMP_ID_CAMERA6` = 105 — exactly the observed fault range.

The PR's stated intent is reasonable: stop MAVLink param messages aimed at
MAVLink cameras from being forwarded onto the CAN bus. But the same handler
immediately assigns:

```cpp
req.node_id = req_list.target_component;   // :87
req.node_id = set.target_component;        // :146
req.node_id = req_read.target_component;   // :225
```

i.e. on this path, the MAVLink component namespace *is* the UAVCAN node-ID
namespace. Excluding 100–105 from the bridge therefore excludes those CAN node
IDs from MAVLink-visible parameter access.

The original PR thread already contains a maintainer note that using CAN node
ID as MAVLink component ID \"is fragile and we should address it properly
sometime in the future.\" This issue is the \"sometime.\"

## Why it hasn't hit more users

ArduPilot's DroneCAN convention assigns ESC node IDs counting **down from 125**
(four motors get 125, 124, 123, 122), which never enters the guarded range.
Users following generic DroneCAN examples that number *up* from 100 land
exactly inside the exclusion.

## Proposed fixes

In order of preference:

### A. Make the camera-vs-CAN-node disambiguation data-driven (preferred)

Only exclude `target_component` 100–105 from the CAN bridge when PX4 has
actually observed a MAVLink camera on that component ID — keyed on recent
HEARTBEATs with `MAV_TYPE_CAMERA`. If PX4 has seen a DroneCAN NodeStatus for
CAN node N but no MAVLink camera heartbeat for comp ID N, forward to CAN. If
both exist, prefer the camera and `PX4_WARN` the collision.

This preserves #25651's intent for real cameras while unblocking the common
DroneCAN ESC case.

### B. Separate the two namespaces

Introduce a distinct component-ID range (or a dedicated MAVLink message / an
explicit CAN-node selector field) for addressing DroneCAN nodes, so the two
namespaces stop overlapping entirely. This is the clean long-term fix and
matches the maintainer's comment on #25651. Requires coordinated QGC-side
changes.

### C. Narrow revert (stopgap)

Revert the 100–105 exclusion from `main`, `release/1.17`, and `release/1.16`,
and re-open the original camera-routing problem #25651 was addressing. This
reinstates that smaller issue but clears the far larger DroneCAN regression.
Acceptable only until A or B lands.

## Affected code

- `src/modules/mavlink/mavlink_parameters.cpp` — the three `MAVLINK_MSG_ID_*`
  branches listed above.

## References

- PR #25651 (introduces regression on `main`):
  https://github.com/PX4/PX4-Autopilot/pull/25651
- PR #25658 (backport to `release/1.16`, shipped in v1.16.1):
  https://github.com/PX4/PX4-Autopilot/pull/25658
- MAVLink component IDs:
  https://mavlink.io/en/messages/minimal.html#MAV_COMPONENT

### PR DESCRIPTION
**Pull request by dakejahl**
## Summary

Only exclude `target_component` 100–105 from the MAVLink → UAVCAN parameter bridge when PX4 has observed a MAVLink camera heartbeat (`MAV_TYPE_CAMERA`) on that component ID within the last 5 seconds. When no camera has been seen there, forward to the matching UAVCAN node as before.

## Context

The bridge in `mavlink_parameters.cpp` maps `target_component` 1:1 onto UAVCAN `node_id`. PR #25651 added an unconditional exclusion of 100–105 (`MAV_COMP_ID_CAMERA..MAV_COMP_ID_CAMERA6`) from the bridge, which also made DroneCAN peripherals at those node IDs unreachable via `PARAM_REQUEST_LIST` / `PARAM_SET` / `PARAM_REQUEST_READ`.

Field symptom: QGroundControl's parameter download hangs / times out when a DroneCAN ESC is powered at a node ID in 100–105. Node IDs outside that range are unaffected. The ArduPilot convention (ESC node IDs counting down from 125) means users following that convention rarely hit this, which is why the regression escaped detection.

Full analysis and alternatives in #27180 (this implements option A).

## Approach

`MavlinkReceiver` already publishes `camera_status` (`timestamp`, `active_comp_id`) on every `MAV_TYPE_CAMERA` heartbeat. `MavlinkParametersManager` now subscribes to `camera_status`, caches the last-seen time per comp ID in `MAV_COMP_ID_CAMERA..MAV_COMP_ID_CAMERA6`, and replaces the raw 100–105 range guard at the three bridge sites with `!is_observed_mavlink_camera(target_component)` — true only when a camera heartbeat was seen on that ID within `CAMERA_OBSERVATION_TIMEOUT` (5 s).

Preserves #25651's intent for real MAVLink cameras; unblocks DroneCAN peripherals assigned IDs in 100–105.

## Deconfliction

A second commit adds a one-shot warning for the actual-collision case: when PX4 sees both a `MAV_TYPE_CAMERA` heartbeat and an online DroneCAN node at the same comp ID in 100–105, it emits `mavlink_log_warning` like:

> CAN node 100 blocked by MAV camera (reassign ID)

Fires regardless of which side joined first, sticky per comp ID for the boot. Only triggers when both conditions hold — users with a camera but no CAN collision see nothing. `dronecan_node_status` is a pre-existing multi-instance uORB topic published by the UAVCAN driver, so no cross-module coupling is added beyond one subscription.

Builds clean locally on `ark_fmu-v6x_default` (exercises the UAVCAN path) and `px4_sitl_default` (non-UAVCAN, `#ifdef`'d out). `make check_format` passes.

## References

- Fixes #27180
- Regression introduced in #25651 (main) / #25658 (release/1.16, v1.16.1)

### CODE REVIEW

File: src/modules/mavlink/mavlink_parameters.h [hunk 1]
```diff
@@ -48,13 +48,16 @@
...
+#include <uORB/SubscriptionMultiArray.hpp>
 #include <uORB/topics/rc_parameter_map.h>
 #include <uORB/topics/parameter_update.h>
 #include <drivers/drv_hrt.h>
 
 #if defined(CONFIG_MAVLINK_UAVCAN_PARAMETERS)
 # include <uORB/topics/uavcan_parameter_request.h>
 # include <uORB/topics/uavcan_parameter_value.h>
+# include <uORB/topics/camera_status.h>
+# include <uORB/topics/dronecan_node_status.h>
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_parameters.h:60]: I don't really like the added coupling here

Comment (julianoes) [reply src/modules/mavlink/mavlink_parameters.h:60]: Does it still compile when you don't build with DroneCAN, or does it need an ifdef?

File: src/modules/mavlink/mavlink_parameters.cpp [hunk 2]
```diff
@@ -58,9 +58,95 @@ MavlinkParametersManager::get_size()
...
+		    || hrt_elapsed_time(&_camera_comp_last_seen[i]) >= CAMERA_OBSERVATION_TIMEOUT) {
+			continue;
+		}
+
+		const uint8_t comp_id = MAV_COMP_ID_CAMERA + i;
+
+		if (is_dronecan_node_online(comp_id)) {
+			_camera_cannode_collision_warned_mask |= warn_bit;
+			mavlink_log_warning(_mavlink.get_mavlink_log_pub(),
+					    "CAN node %u blocked by MAV camera (reassign ID)\t",
```
Comment (julianoes) [inline src/modules/mavlink/mavlink_parameters.cpp:102]: Nice!

**Review by julianoes — COMMENTED** [review]
Not pretty but better than broken for sure.

File: src/modules/mavlink/mavlink_parameters.h (hunk 1 above)
Comment (dakejahl) [reply src/modules/mavlink/mavlink_parameters.h:60]: Yes, all uORB topics are included in all builds

File: src/modules/mavlink/mavlink_parameters.cpp [hunk 3]
```diff
@@ -58,9 +58,95 @@ MavlinkParametersManager::get_size()
...
+		return false;
+	}
+
+	return hrt_elapsed_time(&last_seen) < CAMERA_OBSERVATION_TIMEOUT;
+}
+
+bool
+MavlinkParametersManager::is_dronecan_node_online(uint8_t node_id)
+{
+	dronecan_node_status_s status;
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_parameters.cpp]:
```suggestion
	dronecan_node_status_s status {};
```

File: src/modules/mavlink/mavlink_parameters.cpp [hunk 4]
```diff
@@ -58,9 +58,95 @@ MavlinkParametersManager::get_size()
 	return MAVLINK_MSG_ID_PARAM_VALUE_LEN + MAVLINK_NUM_NON_PAYLOAD_BYTES;
 }
 
+#if defined(CONFIG_MAVLINK_UAVCAN_PARAMETERS)
+
+void
+MavlinkParametersManager::update_observed_camera_components()
+{
+	camera_status_s cam_status;
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_parameters.cpp]:
```suggestion
	camera_status_s cam_status {};
```

**Review by julianoes — APPROVED** [review]
