### PR TITLE
fix(mathlib): correct MedianFilter comparator to satisfy strict-weak …

### LINKED ISSUE #25917: [Bug] MedianFilter comparator function is incorrect, may cause wrong median calculation
### Describe the bug

`math::MedianFilter<…>` uses a comparator that does not implement a strict-weak ordering. When any sliding window contains `NaN`, the subsequent `qsort()` call cannot establish a deterministic order due to undefined comparison behavior. Consequently, the reported median may oscillate among the correct value, a finite extreme, and `NaN`. In some cases, the output remains `NaN` longer than expected, even when incoming finite samples are stable.

#### Root causes

The comparator in [src/lib/mathlib/math/filter/MedianFilter.hpp](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/lib/mathlib/math/filter/MedianFilter.hpp) is defined as:

    static int cmp(const void *a, const void *b)
    {
        return (*(T *)a >= *(T *)b) ? 1 : -1;
    }

Such implementation has following concerns:

- **Irreflexivity violation:** `cmp(x, x)` returns `+1` instead of `0`.
- **Antisymmetry violation:** For any pair `(x, y)` where at least one operand is `NaN`, `cmp(x, y)` may equal `cmp(y, x)` (both `–1`), breaking the rule `cmp(x, y) = –cmp(y, x)`.
- **Undefined NaN policy:** No total order is defined for non-finite values, so sort results depend on the permutation of inputs whenever `NaN` is present.

Because `qsort()` assumes a strict-weak-ordering comparator, these violations make the sorted order undefined, rendering the computed “median” unstable across identical multisets with different input permutations. Our preliminary test shows:
<p align="center">
  Image
</p>

---

### Impact

This flaw manifests as control-adjacent instability in several modules that depend on the median output:

- **[RangeFinder – Fog Check](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/modules/ekf2/EKF/aid_sources/range_finder/sensor_range_finder.cpp#L152):**  
  The median distance used for gating (`_is_blocked`) flips spuriously when windows include `NaN` and finite samples (e.g., `{NaN, NaN, 3, 50, 50}` in varying permutations).

- **[Gyroscope Calibration](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/modules/commander/gyro_calibration.cpp):**  
  Axis-wise medians compared against offsets (`xdiff/ydiff/zdiff`) may exceed acceptance thresholds under a stationary airframe because the median intermittently becomes `NaN` or drifts.

- **[GyroFFT](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/modules/gyro_fft/GyroFFT.cpp):**  
  Median smoothing of per-axis peak frequencies can intermittently output `NaN` or swapped slot values in `sensor_gyro_fft.peak_frequencies_*`, causing jitter in dynamic-notch selection.

- **[RPM Capture](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/drivers/rpm_capture/RPMCapture.cpp):**  
  `_rpm_median_filter.apply(rpm_raw)` occasionally yields `NaN` or mis-ranked medians, perturbing the downstream low-pass filter and RPM estimation.

Although some downstream validation functions happen to suppress non-finite values (e.g., in-range checks reject `NaN` as “out of range”), these checks only mask symptoms rather than fix the underlying comparator flaw. Under adversarial conditions, this vulnerability could potentially be exploited into a denial-of-service–like attack by injecting invalid or contaminated sensor readings that propagate into control loops.

### To Reproduce

A straightforward way to expose the flaw is to inject distance-sensor readings into `DISTANCE_SENSOR` using a custom Python injector. The injector continuously sends synthetic MAVLink `DISTANCE_SENSOR` messages over UDP (`udpin:0.0.0.0:14540`), alternating between nominal distances and non-finite values to emulate outliers.

In the proof-of-concept experiment, a repeating 5-sample sequence was used:

    [NaN, NaN, 3, 50, 50, …]

To temporarily bypass the range check (`< min_cm && > max_cm`) inside [mavlink_receiver.cpp](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/modules/mavlink/mavlink_receiver.cpp) when publishing distance messages, the following modification was added:

    if (dist_sensor.current_distance > 60000u && dist_sensor.current_distance < 62000u) {
        ds.current_distance = NAN;
        // Distances between 600 m and 620 m are interpreted as NaN
        // for emulating invalid sensor readings.
    }

This setup allows `NaN` values to reach the median filter through the normal PX4 message path. Specifically, the behavior of [SensorRangeFinder::updateFogCheck()](https://github.com/PX4/PX4-Autopilot/blob/acef86cb4d4c3994f9a33474e9138c5e4f6c7a7e/src/modules/ekf2/EKF/aid_sources/range_finder/sensor_range_finder.cpp#L152) in `sensor_range_finder.cpp` was observed, where the median is computed as:

    const float median_dist = _median_dist.apply(dist_bottom);

The `median_dist` is then used in the blocked-by-fog condition checks:

    const float factor = 2.f; // magic hardcoded factor

    if (!_is_blocked && median_dist < _max_fog_dist && _prev_median_dist - median_dist > factor * _max_fog_dist) {
        _is_blocked = true;

    } else if (_is_blocked && median_dist > factor * _max_fog_dist) {
        _is_blocked = false;
    }

The `_is_blocked` signal is later used to represent the validity of the range reading. Under our exploitation, the calculated median and the `_is_blocked` status overtime can be:

<p align="center">
Image
</p>

The raw data was captured using uORB::Publication<debug_array_s> and recorded into the flight logs.

### Expected behavior

For each 5-sample window (`{NaN, NaN, 3, 50, 50}`), the median should consistently be **50 m**, representing the stable finite readings after filtering.

However, recordings of `median_dist` via `uORB::Publication<debug_array_s>` show that the reported median alternates unpredictably among **50**, **3**, and **NaN**.

A well-defined median filter should be permutation-invariant even when non-finite values appear. The comparator should either:

1. Ignore non-finite samples when computing the median (returning `NaN` only when all entries are non-finite), or  
2. Define a total order that includes `NaN` (e.g., `finite < NaN`) and return negative, zero, or positive values accordingly.

Either approach would guarantee a stable and robust median that is independent of input permutation. Consequently, downstream modules—fog-check gating, calibration acceptance, dynamic-notch tracking, and RPM estimation—would remain consistent even in the presence of `NaN` values.

### Software Version

v1.16.0 - Stable Release

### Vehicle type

Multicopter

### PR DESCRIPTION
**Pull request by cav2094**
## Summary
Fixes #25917

The `MedianFilter` comparator violated strict-weak ordering, producing non-deterministic medians whenever NaN values entered the sliding window. This caused observable instability in rangefinder fog detection, gyroscope calibration, GyroFFT notch selection, and RPM estimation.

## Root Cause
The original comparator:
```cpp
return (*(T *)a >= *(T *)b) ? 1 : -1;
```
has two flaws:
- Never returns `0`, violating irreflexivity
- `>=` with NaN always evaluates to `false`, causing `cmp(NaN, x)` and `cmp(x, NaN)` to both return `-1`, violating antisymmetry

`qsort` assumes strict-weak ordering — these violations produce undefined sort results.

## Fix
Explicitly intercept NaN before comparison operators are invoked, defining a total order where NaN sorts high. This ensures finite values cluster at the low end of the sorted buffer, and the middle index consistently yields a finite median when the majority of the window is finite.

The NaN checks are guarded with `if constexpr (std::is_floating_point_v<T>)` since the filter is also instantiated with `uint16_t`, for which NaN is not applicable.

## Testing
- All existing `MedianFilterTest` unit tests pass
- Added NaN-specific test cases covering majority-finite and majority-NaN windows

### CODE REVIEW

File: src/lib/mathlib/math/filter/MedianFilter.hpp [hunk 1]
```diff
@@ -44,6 +44,13 @@
 #include <stdlib.h>
 #include <stdint.h>
 #include <string.h>
+#include <px4_platform_common/defines.h>
+
+// Minimal float detection without headers
+template<typename U> struct px4_is_floating_point   { static constexpr bool value = false; };
+template<> struct px4_is_floating_point<float>       { static constexpr bool value = true; };
```
Comment (dakejahl) [inline src/lib/mathlib/math/filter/MedianFilter.hpp]:
```suggestion
template<typename U> struct px4_is_floating_point { static constexpr bool value = false; };
template<> struct px4_is_floating_point<float> { static constexpr bool value = true; };
```
don't manually align, single space only

File: src/lib/mathlib/math/filter/MedianFilter.hpp [hunk 2]
```diff
@@ -82,7 +89,18 @@ class MedianFilter
 
 	static int cmp(const void *a, const void *b)
 	{
-		return (*(T *)a >= *(T *)b) ? 1 : -1;
+		const T va = *(const T *)a;
+		const T vb = *(const T *)b;
+
+		 if constexpr (px4_is_floating_point<T>::value) {
+			if(!PX4_ISFINITE(va) && !PX4_ISFINITE(vb)) { return  0; }
```
Comment (dakejahl) [inline src/lib/mathlib/math/filter/MedianFilter.hpp]:
```suggestion
			if (!PX4_ISFINITE(va) && !PX4_ISFINITE(vb)) { return  0; } 
```
add space after if

File: src/lib/mathlib/math/filter/MedianFilter.hpp [hunk 3]
```diff
@@ -44,6 +44,13 @@
...
+#include <px4_platform_common/defines.h>
+
+// Minimal float detection without headers
+template<typename U> struct px4_is_floating_point { static constexpr bool value = false; };
+template<> struct px4_is_floating_point<float> { static constexpr bool value = true; };
+template<> struct px4_is_floating_point<double> { static constexpr bool value = true; };
+template<> struct px4_is_floating_point<long double> { static constexpr bool value = true; };
 
 namespace math
 {
```
Comment (dakejahl) [inline src/lib/mathlib/math/filter/MedianFilter.hpp]:
```suggestion
#include <px4_platform_common/defines.h>

namespace math
{

template<typename U> struct px4_is_floating_point { static constexpr bool value = false; };
template<> struct px4_is_floating_point<float> { static constexpr bool value = true; };
template<> struct px4_is_floating_point<double> { static constexpr bool value = true; };
template<> struct px4_is_floating_point<long double> { static constexpr bool value = true; };
```

**Review by cav2094 — COMMENTED** [review]
Thanks for patience
