### PR TITLE
Commander: lock down mav_sys_id and mav_comp_id

### LINKED ISSUE #22542: mav_sys_id change causes unresponsive system
### Describe the bug

If you change mav_sys_id to ≠ 1 you can not reboot or change anything from QGC. 

manually rebooting works but then I needed to get out a debug probe to access the fmu to reset the param...

### To Reproduce

Used a few different versions of 1.14 release.

Setup a plane and then set mav_sys_id to 2 or 3.

Try and reboot via QGC and you should get a failed to reboot.

I would not recommend doing a manual reboot since you need to set it from a debug board to fix it...

### Expected behavior

Should work as previously and have be able to have multiple vehicles on the same network..

### Screenshot / Media

_No response_

### Flight Log

none made

### Software Version

1.14 release

### Flight controller

v6c

### Vehicle type

Fixed Wing

### How are the different components wired up (including port information)

_No response_

### Additional context

Tried 3 different hardwares and software combos (and different versions of qgc between 4.2.9 and 4.3.0)

### PR DESCRIPTION
**Pull request by mrpollo**
Only allow setting `MAV_SYS_ID` and `MAV_COMP_ID` when initializing commander, similar to the implementation in the mavlink module.

fixes #22542 

https://github.com/user-attachments/assets/147dd037-4317-4ac7-b9da-4ecb09c73171

### CODE REVIEW

File: src/modules/commander/Commander.cpp [hunk 1]
```diff
@@ -1682,15 +1694,8 @@ void Commander::updateParameters()
...
-	// MAV_SYS_ID => vehicle_status.system_id
-	if ((_param_mav_sys_id != PARAM_INVALID) && (param_get(_param_mav_sys_id, &value_int32) == PX4_OK)) {
-		_vehicle_status.system_id = value_int32;
-	}
-
-	// MAV_COMP_ID => vehicle_status.component_id
-	if ((_param_mav_comp_id != PARAM_INVALID) && (param_get(_param_mav_comp_id, &value_int32) == PX4_OK)) {
-		_vehicle_status.component_id = value_int32;
-	}
+	// NOTE: The system can't handle changing the system_id, and component_id in the same session
```
Comment (dagar) [inline src/modules/commander/Commander.cpp:1697]: Comment needs to go with MAV_SYS_ID/MAV_COMP_ID.

It's also not that the system can't handle it, but that immediately on change (from a GCS) the GCS would need to be aware of the new SYS ID.

Comment (dagar) [inline src/modules/commander/Commander.cpp:1697]:
```suggestion
```

File: src/modules/commander/Commander.cpp [hunk 2]
```diff
@@ -1682,15 +1694,8 @@ void Commander::updateParameters()
...
+	// you need to reboot the vehicle for settings to change
```
Comment (dagar) [inline src/modules/commander/Commander.cpp:1698]:
```suggestion
```

File: src/modules/commander/Commander.cpp [hunk 3]
```diff
@@ -703,6 +703,18 @@ Commander::Commander() :
 	_param_mav_type = param_find("MAV_TYPE");
 	_param_rc_map_fltmode = param_find("RC_MAP_FLTMODE");
 
+	int32_t value_int32 = 0;
+
+	// MAV_SYS_ID => vehicle_status.system_id
+	if ((_param_mav_sys_id != PARAM_INVALID) && (param_get(_param_mav_sys_id, &value_int32) == PX4_OK)) {
```
Comment (dagar) [inline src/modules/commander/Commander.cpp:709]: Get rid of `_param_mav_sys_id` in the header, we can just do it locally and not store anything.

```suggestion
	param_t param_mav_sys_id = param_find("MAV_SYS_ID");
	if ((param_mav_sys_id != PARAM_INVALID) && (param_get(param_mav_sys_id, &value_int32) == PX4_OK)) {
```

File: src/modules/commander/Commander.cpp [hunk 4]
```diff
@@ -703,6 +703,18 @@ Commander::Commander() :
...
+		_vehicle_status.system_id = value_int32;
+	}
+
+	// MAV_COMP_ID => vehicle_status.component_id
+	if ((_param_mav_comp_id != PARAM_INVALID) && (param_get(_param_mav_comp_id, &value_int32) == PX4_OK)) {
```
Comment (dagar) [inline src/modules/commander/Commander.cpp:714]:
```suggestion
	param_t param_mav_comp_id = param_find("MAV_COMP_ID");
	if ((param_mav_comp_id != PARAM_INVALID) && (param_get(param_mav_comp_id, &value_int32) == PX4_OK)) {
```

**Review by dagar — APPROVED** [review]

**Comment by mrpollo** [comment]
cc @ryanjAA

**Comment by ryanjAA** [comment]
@mrpollo thanks :) 

Backported and tested on local 1.14. Works as intended.

If interested can backport to release 1.14.
