### PR TITLE
CubeBlack: fix hardware detection

### LINKED ISSUE #21102: Hardware detection doesn't work on Cube Black with CAN1 connected
## Describe the bug
When a CAN peripheral like Here3+ is connected to CAN1 on CubeBlack, the hardware detection fails and the sensors are not started correctly.

With CAN connected the output is:

```
bad version detected, forcing to fmu-v2
FMUv2 ver 0x8 : Rev 0 V2
```

And sometimes it even gets detected as a Mini:
```
FMUv2 ver 0xA : Rev 0 V2M
```

Without it CAN, it's correct:

```
FMUv2 ver 0xE : Rev 0 V30
```

## To Reproduce
1. Flash px4-fmu-v3 to CubeBlack
2. Connect something on CAN like Here3+
3. Power on using USB
4. Check boot output (e.g. on CONS 3 pin port, pin closest to Cube is GND, then Rx, then Tx)

FYI @davids5 

This is the detection code:
https://github.com/PX4/PX4-Autopilot/blob/b9f9f25b48d817b81006ae1052d9b0152cf06a8e/boards/px4/fmu-v3/src/init.c#L168-L240

### PR DESCRIPTION
**Pull request by julianoes**
This fixes the case where the hardware detection fails on CubeBlack when a CAN device is connected to CAN1 and talking, and therefore preventing the check from getting a clear result.

I suggest to review commit by commit as the first commit is just a refactor.

Tested on CubeBlack.

Fixes #21102.

Probably needs duplicating/copying to fmu-v2.

### CODE REVIEW

**Comment by davids5** [comment]
@julianoes Did you test on V2 and a mini?

**Comment by julianoes** [comment]
> @julianoes Did you test on V2 and a mini?

I did not. I can do that next week. I don't have the hardware with me at the moment.

**Comment by julianoes** [comment]
@davids5 I was able to test a a few:

- 3DR Pixhawk Mini, without silicon errata:
```
HW arch: PX4_FMU_V3
HW type: V2M
HW version: 0x9000A
HW revision: 0x000
```
- Pixfalcon, with silicon errata:
```
nsh> ver all
HW arch: PX4_FMU_V2
HW type: V2
HW version: 0x90008
HW revision: 0x000
```
Note that this is identical on `main`, so presumably that's correct...

- Original Pixhawk, with silicon errata:
```
nsh> ver all
HW arch: PX4_FMU_V2
HW type: V2
HW version: 0x90008
HW revision: 0x000
```

File: boards/px4/fmu-v3/src/init.c [hunk 1]
```diff
@@ -198,19 +199,18 @@ __EXPORT void board_on_reset(int status)
  *
  ************************************************************************************/
 
-static int determin_hw_version(int *version, int *revision)
+static int determine_hw_version(void)
```
Comment (davids5) [inline boards/px4/fmu-v3/src/init.c:202]: The API with the params `int *version`, `int *revision` is compatible with the real HW revision and version. Why change it?

**Review by davids5 — COMMENTED** [review]
Glad to see this worked. One inline question

**Comment by mrpollo** [comment]
FYI this is going in for v1.14

File: boards/px4/fmu-v3/src/init.c (hunk 1 above)
Comment (julianoes) [reply boards/px4/fmu-v3/src/init.c:202]: I looked at the function declaration and two things caught my eye:
- The revision was never changed, it's always 0, clearly it's not used.
- To be pedantic, the function is called determine hw "version" (and not revision).
- The return value of the function was always 0/OK so it's a bit of a lie that it would tell you when it fails. And the caller also does not actually deal with the return value not being 0/OK which I didn't like either.

Comment (davids5) [reply boards/px4/fmu-v3/src/init.c:202]: All good reason.

In my mind a Version is a type of thing, Revision is how many times it to to get right. Both can have changes that effect HW.  I prefer having one system level interface that supports both, even though we could not support the Revision on the pre exiting HW.  

In retrospect and thinking about a split for FMUM/BASE the name `determin_hw_version`  could be better named as `determin_hw_characteristics` and  2 values could then be interpreted as needed.  Or wrapped in a union of structs with names.

Comment (julianoes) [reply boards/px4/fmu-v3/src/init.c:202]: Ok, I can see that there is actually the function `determine_hw_info` in quite a few places which actually has the arguments swapped. I suppose I should change it to that API?

Comment (davids5) [reply boards/px4/fmu-v3/src/init.c:202]: Yes - I think it would be good to be consistent.

Comment (julianoes) [reply boards/px4/fmu-v3/src/init.c]: Ok, pushed.

**Review by davids5 — APPROVED** [review]
@julianoes Thank you!

**Comment by julianoes** [comment]
Thanks @davids5. The CI error is unrelated, it ran out of internet.

**Comment by davids5** [comment]
> FYI this is going in for v1.14

@mrpollo This is ready from my stand point, please merge if you are ready for it.
