### PR TITLE
fix(mavlink): Allowing custom modes to request offboard setpoints via the external mode registration

### LINKED ISSUE #26768: [Bug] MAVLink/MAVROS Offboard setpoints ignored when OFFBOARD is replaced by external mode
### Describe the bug
When RAPTOR is configured to replace internal OFFBOARD mode, standard MAVLink/MAVROS Offboard setpoints are not routed into PX4 internal setpoint topics.

Current setup:
- `MC_RAPTOR_ENABLE=1`
- `MC_RAPTOR_OFFB=1`
- `MC_RAPTOR_INTREF=0`

In this setup, switching to OFFBOARD is mapped to an external replacement mode (RAPTOR). However, MAVLink setpoints (`SET_POSITION_TARGET_LOCAL_NED`, `SET_POSITION_TARGET_GLOBAL_INT`, `SET_ATTITUDE_TARGET`) are accepted on the wire but not published to internal control topics as expected.

Observed behavior:
1. Enter OFFBOARD (which is replaced by RAPTOR external mode).
2. Send continuous MAVLink/MAVROS Offboard setpoints.
3. `trajectory_setpoint` does not update in RAPTOR control path (or is considered stale), and RAPTOR does not follow the command stream.

Expected behavior:
- If an external mode replaces OFFBOARD, standard MAVLink Offboard setpoints should still be accepted and routed exactly like OFFBOARD, without relaxing gating for unrelated non-Offboard modes.

### Flight Log / Additional Information
Flight log link: N/A (bench/ground validation with topic observation)

Version:
- PX4 git-hash: `d317113dc8b6d41c8304440c8846e69dc511cd4a`
- PX4 version: `1.17.0 40`
- Build variant: `raptor`

Hardware:
- FC: HKUST_NXT_DUAL (`hkust_nxt-dual_raptor`)
- Vehicle type: Multicopter

Related context:
- This blocks MAVROS/MAVLink users from using RAPTOR with external trajectory/attitude targets through standard Offboard messages.
- A generic (non-RAPTOR-specific) fix is preferred so all external OFFBOARD replacements behave consistently.

### PR DESCRIPTION
**Pull request by jonas-eschmann**
### Solved Problem
Fixes #26768

### Solution

This PR implements **Alternative 1**

```
        ┌─────────────────┐
        │  Custom Mode    │
        └─────────────┬───┘
                      │ register_ext_component_request.request_offboard_setpoints
        ┌─────────────┼──────────┐
        │ Commander   |          │
        │ ┌───────────▼────────┐ │
        │ │ ModeManagement     │ │
        │ └────────────────────┘ │
        └────────┬───────────────┘
                 │ vehicle_status.accepts_offboard_setpoints
                 ▼
        ┌─────────────────┐    MAVLink: SET_POSITION_TARGET_LOCAL_NED
        │ MavlinkReceiver │◀───────────────────────────────────────────
        └────────┬────────┘
                 │ trajectory_setpoint
                 ▼
        ┌─────────────────┐
        │  Custom Mode    │
        └─────────────────┘
```

### Changelog Entry
For release notes:
```
Feature/Bugfix #26768 Allowing modes that use the external mode registration to receive offboard setpoints
```

### Alternatives
Approach | Pros | Cons
-- | -- | --
**[GrooveWJH PR](https://github.com/PX4/PX4-Autopilot/pull/26771)**: The Mavlink Receiver observes the external modes through the request topics | No modifications to vehicle status | The Mavlink receiver gets entangled with the mode registration
**Alternative 1**: `request_offboard_setpoints` in the external mode registration. This needs to be reflected in the `vehicle_status`  because that is the main source determining the behavior of the `mavlink_receiver.cpp` |  Cleanest long-term solution  |  adds flag to `vehicle_status`
**Alternative 2**:  Make `mavlink_receiver.cpp` always emit `trajectory_setpoint` for external mode IDs |  one-line fix  | If there is ever an in-source mode that uses the external mode registration but also generates `trajectory_setpoint` itself, they could be conflicting. AFAIK currently only `mc_raptor` and `mc_nn_control` use the external mode registration from the inside and for external modes it does not matter anyways, so this is not an issue

I believe **Alternative 1** is the the right approach here. It unambiguously implements the forwarding while neither entangling `mavlink_receiver.cpp` with the mode registration (in contrast to  **[GrooveWJH PR](https://github.com/PX4/PX4-Autopilot/pull/26771)**) nor adding assumptions about the `NAVIGATION_STATE_EXTERNAL{1-8}`

### Context

External modes like `mc_raptor` and `mc_nn_control` that use the external mode registration benefit greatly from being able to receive offboard setpoints via MAVLink

### CODE REVIEW

File: src/modules/mavlink/mavlink_receiver.cpp [hunk 1]
```diff
@@ -1162,8 +1162,8 @@ MavlinkReceiver::handle_message_set_position_target_local_ned(mavlink_message_t
 			vehicle_status_s vehicle_status{};
 			_vehicle_status_sub.copy(&vehicle_status);
 
-			if (vehicle_status.nav_state == vehicle_status_s::NAVIGATION_STATE_OFFBOARD) {
-				// only publish setpoint once in OFFBOARD
+			if (vehicle_status.accepts_offboard_setpoints) {
+				// only publish setpoint once in mode that accepts offboard setpoints
```
Comment (Jaeyoung-Lim) [inline src/modules/mavlink/mavlink_receiver.cpp:1166]: Why can't we just add external modes here?

Comment (jonas-eschmann) [reply src/modules/mavlink/mavlink_receiver.cpp:1166]: That would be **Alternative 2**. I think **Alternative 1** is cleaner because it is backwards compatible with the current semantics of the mode registration and because it explicitly implements this feature (someone who reads the code should immediately understand what it does and why it exists). 

**Alternative 2** prohibits internal modes that use the external mode registration to generate their own `trajectory_setpoints` because they can not influence if the `mavlink_receiver.cpp` will also publish on that topic, additionally, in my understanding, **Alternative 2** could break existing external modes (that we don't know of because they are out-of-tree) because they might assume that `trajectory_setpoint` is not published. 

I think its a trade-off between more explicit solution (more modifications as well) without side effects vs. one-line solution with some possible side-effects. In my opinion both **Alternative 1/2** are good fixes and both improve the situation and fix #26768. I think either of **Alternative 1/2** is preferable over #26771 where the `mavlink_receiver.cpp` is entangled with the mode-registration. 

@Jaeyoung-Lim Please let me know how to proceed

File: src/modules/commander/ModeManagement.hpp [hunk 2]
```diff
@@ -232,6 +235,11 @@ class ModeManagement : public ModeChangeHandler
 		can_set_nav_state_mask = valid_nav_state_mask & ~(1u << vehicle_status_s::NAVIGATION_STATE_TERMINATION);
 	}
 
+	bool currentModeAcceptsOffboardSetpoints(uint8_t nav_state) const
+	{
+		return nav_state == vehicle_status_s::NAVIGATION_STATE_OFFBOARD;
+	}
+
```
Comment (Pedro-Roque) [inline src/modules/commander/ModeManagement.hpp:242]: So this function will need to be extended to other modes that accept offboard setpoints?

Comment (jonas-eschmann) [reply src/modules/commander/ModeManagement.hpp:242]: `ModeManagement` has two modes: `CONSTRAINED_FLASH` enabled/disabled. If `CONSTRAINED_FLASH` is enabled, the whole external mode registration is turned off. The method you are referring is the overload for that case. The overload for the case where `CONSTRAINED_FLASH` is disabled and external mode registration is in use is [here](https://github.com/jonas-eschmann/PX4-Autopilot/blob/f06499a48a0f975ed07aa34ee1be0aca86bb5505/src/modules/commander/ModeManagement.cpp#L676):

```
bool ModeManagement::currentModeAcceptsOffboardSetpoints(uint8_t nav_state) const
{
	// OFFBOARD mode always accepts offboard setpoints
	if (nav_state == vehicle_status_s::NAVIGATION_STATE_OFFBOARD) {
		return true;
	}

	// Check if it's an external mode that requests offboard setpoints
	if (_modes.valid(nav_state)) {
		return _modes.mode(nav_state).request_offboard_setpoints;
	}

	return false;
}
```

To answer your question: in neither case (`CONSTRAINED_FLASH` enabled/disabled) we need to extend the function to list new modes. The new modes can simply set the `request_offboard_setpoints` flag in the `register_ext_component_request` message.

**Comment by jonas-eschmann** [comment]
@Pedro-Roque 
> Not sure if I prefer this version much more... Also perhaps it could be a good idea to aggregate multiple requests to change message versions before doing so for adding one extra field, unless urgent. Otherwise we will end up with large version numbers soon.

I agree about the message versions. I just bumped the version because otherwise the CI tests complain.

**Comment by GrooveSino** [comment]
> @Pedro-Roque
> 
> > Not sure if I prefer this version much more... Also perhaps it could be a good idea to aggregate multiple requests to change message versions before doing so for adding one extra field, unless urgent. Otherwise we will end up with large version numbers soon.
> 
> I agree about the message versions. I just bumped the version because otherwise the CI tests complain.

Yes, in fact, I was also quite conflicted about whether the message version should be changed when modifying the code. In any case, I hope everyone present can discuss and reach a conclusion as soon as possible. After the merge, I will immediately apply this technology to industry-level scenarios, which was my original intention when I first submitted the PR.

**Comment by Jaeyoung-Lim** [comment]
Thanks @bkueng !
