### PR TITLE
Rover publish actuator controls with rate of gyro

### LINKED ISSUE #17381: Dshot on rover not working
**Describe the bug**
On 1.11.3 with my modalai/fc-v1, When I select Dshot for my rover, my blheli ESCs refuse to initialize, however quad x works and gives the final beeps on power up. It appears the dshot zero command isn't being sent correctly or at all. 

**Expected behavior**
Rover airframes should be able to run Dshot 

**Additional context**
I suspected the rc.rover_defaults lowering the PWM_RATE to be the problem, but commenting that out doesn't fix the problem. I'm not sure what else could be preventing Dshot from operating correctly. I'll attach an oscilloscope soon to see if it's a timing issue or if there's no output at all.

### PR DESCRIPTION
**Pull request by benjinne**
**Describe problem solved by this pull request**
Fixes #17381 
Fix Dshot not initializing on certain ESCs requiring update rate faster than 250Hz, by making the actuator update configurable by adjusting the IMU_GYRO_RATEMAX parameter. 

**Describe your solution**
Make Rover update on `vehicle_angular_velocity` instead of `vehicle_attitude`

**Describe possible alternatives**
Increase the rate of `vehicle_attitude`

**Test data / coverage**
Tested on the modalai/fc_v1 board by selecting rover and measuring update rate with oscilloscope and `uorb top actuator` to confirm the actuator_output rate increased.

### CODE REVIEW

**Comment by benjinne** [comment]
I need to test on my rover, and determine why unit test is failing. Any feedback is appreciated.

**Review by LorenzMeier — DISMISSED** [review]
Looks like a good next step!

File: src/modules/rover_pos_control/RoverPositionControl.cpp [hunk 1]
```diff
@@ -385,7 +385,10 @@ RoverPositionControl::Run()
 {
 	parameters_update(true);
 
-	if (_vehicle_attitude_sub.update(&_vehicle_att)) {
```
Comment (bkueng) [inline src/modules/rover_pos_control/RoverPositionControl.cpp:388]: You still need to update `_vehicle_att`

Comment (benjinne) [reply src/modules/rover_pos_control/RoverPositionControl.cpp:388]: Done. Added vehicle_attitude_poll

**Review by benjinne — COMMENTED** [review]
Sim waypoints work again, and actuator_output is still increased

**Review by bkueng — APPROVED** [review]
