### PR TITLE
fix(mavlink)!: align signing with MAVLink spec and fix performance regression

### LINKED ISSUE #26893: [Bug] Mavlink very slow & broken
### Describe the bug

Since merging [mavlink signing support](https://github.com/PX4/PX4-Autopilot/pull/25284), mavlink messages are CONSIDERABLY slower than before. Faster streams do not acchieve their set frequency any more. Also, it seems like a lot of messages are just "dropped", and never actually arrive at the GCS, even with the best link possible. 

This leads to massive issues:

1. Slow communication to the GCS
2. mavlink shell sometimes broken/unresponsive
3. More frequent mission sync timeout
4. Broken GCS due to missing capability response (mavlink v2 gets blocked)
5. Parameter saving issues

Note that some of these issues are sporadic. 

## Before:

Image

## After:
Image

### PR DESCRIPTION
**Pull request by mrpollo**
## Summary

Reworks MAVLink signing to align with the MAVLink specification and fix the performance regression reported in #26893.

The previous implementation added a `MAV_SIGN_CFG` parameter that set `MAVLINK_SIGNING_FLAG_SIGN_OUTGOING` unconditionally, running SHA-256 on every outgoing packet even with signing "off." It also restricted `SETUP_SIGNING` to USB only, which is narrower than the spec requires.

## What MAVLink signing protects against

MAVLink signing prevents message injection and spoofing over wireless links. An attacker within radio range cannot send commands to the vehicle or tamper with messages in flight. It does not encrypt messages (telemetry is still readable) and does not protect against physical access to the SD card where the key is stored.

## How it works now

- **Enable**: Send `SETUP_SIGNING` with a valid key on any link. When no key exists, the message is accepted unsigned. When a key is already active, the message must be signed with the current key.
- **Disable**: Send `SETUP_SIGNING` with an all-zero key and timestamp. The message must be signed with the current key. Alternatively, delete `/mavlink/mavlink-signing-key.bin` from the SD card and reboot.
- **Armed guard**: `SETUP_SIGNING` is rejected while the vehicle is armed, for both enable and disable.
- **No key, no overhead**: When no key is present, the signing struct is not wired into the MAVLink library. Zero CPU or bandwidth cost.
- **Key storage**: 32-byte key + 8-byte timestamp stored at `/mavlink/mavlink-signing-key.bin`. Persists across reboots.
- **Propagation**: Key changes on one link propagate to all mavlink instances.

## Changes

- Remove `MAV_SIGN_CFG` parameter
- Only set `MAVLINK_SIGNING_FLAG_SIGN_OUTGOING` when a valid key is present
- Accept `SETUP_SIGNING` on any link, not just USB
- Reject `SETUP_SIGNING` while armed
- Allow disabling signing via signed all-zero key
- Treat duplicate disable as no-op (QGC sends twice for reliability)
- Update signing and security hardening documentation

## Testing

Tested with QGroundControl daily build against PX4 SITL (SIH):

- Enable signing from QGC: key accepted, comms continue signed
- Enable signing while armed: rejected, signing stays off
- Disable signing from QGC: signed blank key accepted, comms revert to unsigned
- Disable signing while armed: rejected, signing stays active
- Key persistence: restart SITL, signing still active, QGC reconnects
- Physical disable: delete key file, restart, signing off, QGC reconnects after disabling its key

Found a QGC-side bug during testing: QGC does not check for `SETUP_SIGNING` rejection and enables local signing unconditionally, causing comms loss when PX4 rejects. Will file separately. https://github.com/mavlink/qgroundcontrol/issues/14250

Fixes #26893

### CODE REVIEW

File: src/modules/mavlink/mavlink_main.cpp [hunk 1]
```diff
@@ -97,10 +97,12 @@ mavlink_message_t *mavlink_get_channel_buffer(uint8_t channel) { return mavlink_
 
 static bool accept_unsigned_callback(const mavlink_status_t *status, uint32_t message_id)
 {
-	Mavlink *m = Mavlink::get_instance_for_status(status);
+	for (int i = 0; i < MAVLINK_COMM_NUM_BUFFERS; i++) {
+		Mavlink *inst = mavlink_module_instances[i];
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_main.cpp]: This needs a mutex.

**Review by dakejahl — COMMENTED** [review]
I quickly looked through the code to see the usage of `mavlink_module_mutex` and it looks like it's kind of a mess. I don't think this mutex is really providing the protection it's supposed to provide. There are race conditions where a pointer to a mavlink instance is returned, and that mavlink instance could get deleted while another function still holds that pointer.

**Comment by mrpollo** [comment]
@dakejahl Good catch on the mutex issues. I've opened #26895 to track the broader `mavlink_module_mutex` thread safety problems you identified, plus the signing-specific thread safety items found during spec review (global signing streams, key transition atomicity).

These predate this PR and should be addressed as a follow-up once the signing cleanup lands.

File: src/modules/mavlink/mavlink_main.cpp [hunk 2]
```diff
@@ -97,10 +97,12 @@ mavlink_message_t *mavlink_get_channel_buffer(uint8_t channel) { return mavlink_
...
 
-	if (m != nullptr) {
-		return m -> accept_unsigned(m->sign_mode(), m -> is_usb_uart(), message_id);
+		if (inst != nullptr && inst->get_status() == status) {
+			return inst->accept_unsigned(message_id);
+		}
 	}
```
[the remark this answers is not in the document]
Comment (mrpollo) [reply src/modules/mavlink/mavlink_main.cpp:108]: Pre-existing pattern -- the C callbacks at the top of this file (mavlink_send_uart_bytes, etc.) have always accessed mavlink_module_instances[] without the mutex. Tracked in #26895.

File: src/modules/mavlink/mavlink_main.cpp [hunk 3]
```diff
@@ -1054,10 +1042,37 @@ Mavlink::handle_message(const mavlink_message_t *msg)
...
+				send_statustext_info("MAVLink signing key accepted");
+
+				// Propagate new key to all other mavlink instances
+				for (int i = 0; i < MAVLINK_COMM_NUM_BUFFERS; i++) {
+					Mavlink *inst = mavlink_module_instances[i];
+
+					if (inst != nullptr && inst != this) {
+						inst->reload_signing_key();
+					}
+				}
```
[the remark this answers is not in the document]
Comment (mrpollo) [reply src/modules/mavlink/mavlink_main.cpp]: Same pre-existing pattern. Tracked in #26895.

File: src/modules/mavlink/mavlink_sign_control.cpp [hunk 4]
```diff
@@ -92,99 +92,122 @@ void MavlinkSignControl::start(int _instance_id, mavlink_status_t *_mavlink_stat
...
+{
+	if (_is_signing_initialized) {
+		_mavlink_signing.flags = MAVLINK_SIGNING_FLAG_SIGN_OUTGOING;
+		_mavlink_status->signing = &_mavlink_signing;
+		_mavlink_status->signing_streams = &global_mavlink_signing_streams;
+
+	} else {
+		_mavlink_signing.flags = 0;
+		_mavlink_status->signing = nullptr;
+		_mavlink_status->signing_streams = nullptr;
```
[the remark this answers is not in the document]
Comment (mrpollo) [reply src/modules/mavlink/mavlink_sign_control.cpp:199]: Good catch. Added a null guard in reload_key() -- if _mavlink_status hasn't been set yet, we bail out early. Fixed.

File: src/modules/mavlink/mavlink_sign_control.cpp [hunk 5]
```diff
@@ -92,99 +92,122 @@ void MavlinkSignControl::start(int _instance_id, mavlink_status_t *_mavlink_stat
...
+	}
```
[the remark this answers is not in the document]
Comment (mrpollo) [reply src/modules/mavlink/mavlink_sign_control.cpp:200]: Pre-existing thread safety issue. Tracked in #26895 for follow-up.

File: src/modules/mavlink/mavlink_main.cpp [hunk 6]
```diff
@@ -1054,10 +1042,37 @@ Mavlink::handle_message(const mavlink_message_t *msg)
 	 *  NOTE: this is called from the receiver thread
 	 */
 
-	if (is_usb_uart()) {
-		if (_sign_control.check_for_signing(msg)) {
-			return;
+	// SETUP_SIGNING must never be forwarded to other links (MAVLink spec requirement).
+	// Only process it on USB; silently drop on all other links.
+	if (msg->msgid == MAVLINK_MSG_ID_SETUP_SIGNING) {
+		if (is_usb_uart()) {
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_main.cpp]: I don't think this is correct. You should be able to setup signing over any link.

Comment (mrpollo) [reply src/modules/mavlink/mavlink_main.cpp]: yes agreed, no special use cases, its all or nothing, and you better not loose the key!

File: src/modules/mavlink/mavlink_main.cpp (hunk 1 above)
Comment (mrpollo) [reply src/modules/mavlink/mavlink_main.cpp]: I think this whole code should be improved, and we should do a pass soon for 1.18 or 1.19

Comment (dakejahl) [inline src/modules/mavlink/mavlink_main.cpp]: This iterates `mavlink_module_instances` without holding `mavlink_module_mutex`. The old code called `get_instance_for_status()` which properly acquired the lock.

This callback is invoked from the MAVLink library's parsing path in the receiver thread. If another thread tears down an instance (setting `mavlink_module_instances[i] = nullptr` at line ~3003), you could read a stale non-null pointer after the null check passes, then dereference a destroyed object.

Every other iteration of this array in this file acquires the lock (`forward_message`, `instance_count`, `get_instance_for_device`, `serial_instance_exists`, `component_was_seen`, etc.).

Suggested fix: add `LockGuard lg{mavlink_module_mutex};` before the loop.

File: src/modules/mavlink/mavlink_main.cpp [hunk 7]
```diff
@@ -1054,10 +1042,57 @@ Mavlink::handle_message(const mavlink_message_t *msg)
...
 		}
+
+		MavlinkSignControl::SetupSigningResult result = _sign_control.check_for_signing(msg);
+
+		switch (result) {
+		case MavlinkSignControl::KEY_ACCEPTED:
+			send_statustext_info("MAVLink signing key accepted");
+
+			// Propagate new key to all other mavlink instances
+			for (int i = 0; i < MAVLINK_COMM_NUM_BUFFERS; i++) {
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_main.cpp]: Two issues:

**1. Missing mutex** — Same concern as the callback above: iterates `mavlink_module_instances` without `mavlink_module_mutex`. Needs `LockGuard`.

**2. Duplicate code** — This loop is identical to the `SIGNING_DISABLED` case at line ~1077. Consider extracting a propagation helper, or restructuring the switch so both cases share the loop:

```cpp
switch (result) {
case MavlinkSignControl::KEY_ACCEPTED:
    send_statustext_info("MAVLink signing key accepted");
    break;
case MavlinkSignControl::SIGNING_DISABLED:
    send_statustext_info("MAVLink signing disabled");
    break;
// ...
}

if (result == MavlinkSignControl::KEY_ACCEPTED || result == MavlinkSignControl::SIGNING_DISABLED) {
    LockGuard lg{mavlink_module_mutex};
    for (int i = 0; i < MAVLINK_COMM_NUM_BUFFERS; i++) {
        Mavlink *inst = mavlink_module_instances[i];
        if (inst != nullptr && inst != this) {
            inst->reload_signing_key();
        }
    }
}
```

File: src/modules/mavlink/mavlink_sign_control.cpp [hunk 8]
```diff
@@ -92,99 +92,145 @@ void MavlinkSignControl::start(int _instance_id, mavlink_status_t *_mavlink_stat
...
+	_is_signing_initialized = true;
+
+	_update_signing_state();
 	write_key_and_timestamp();
 
-	return true;
+	return KEY_ACCEPTED;
+}
+
+void MavlinkSignControl::reload_key()
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_sign_control.cpp:155]: `reload_key()` is called from instance A's receiver thread on instance B's `_sign_control`. It mutates:
- `_mavlink_signing.secret_key` (32 bytes, via `::read()` then potentially `memset`)
- `_mavlink_signing.timestamp` (8 bytes)
- `_mavlink_signing.flags`
- `_mavlink_status->signing` (pointer, set to `&_mavlink_signing` or `nullptr`)

Meanwhile, instance B's receiver thread may be mid-parse in the MAVLink library, reading the same `_mavlink_signing` struct for signature verification. This is a **torn read** — B could see a mix of old and new key bytes, causing valid signed messages to be rejected (or worse, incorrectly accepted during the transition window).

A safer pattern: instead of mutating another instance's state cross-thread, set an atomic `_key_dirty` flag and let each instance reload its own key on its own thread (e.g., check the flag at the top of the receive loop). This avoids cross-thread mutation of the signing struct entirely.

**Review by dakejahl — COMMENTED** [review]
## Review Summary

Good design direction — aligning with the MAVLink spec and eliminating SHA-256 overhead when signing is off is the right fix for #26893. The documentation updates are thorough and honest (the "what signing does NOT protect against" table is particularly good).

However, there are **thread safety issues** in the new code that should be addressed before merging:

| # | Issue | Severity |
|---|-------|----------|
| 1 | `accept_unsigned_callback` iterates `mavlink_module_instances` without `mavlink_module_mutex` — regression from old code which used `get_instance_for_status()` (locked) | **High** |
| 2 | `reload_key()` called cross-thread: instance A's receiver thread mutates instance B's `_mavlink_signing` struct while B's receiver thread may be reading it for signature verification (torn read) | **High** |
| 3 | Propagation loops in `handle_message` also iterate `mavlink_module_instances` without the mutex | **High** |
| 4 | HEARTBEAT added to unsigned allowlist expands attack surface (spec-aligned, but worth a code comment) | **Low** |

### What's good

- Zero overhead when signing is off (not wiring the signing struct when no key present) is the correct fix
- Removing `O_CREAT` from the read path — old code created empty key file even when no key existed
- Clean `SetupSigningResult` enum replacing the boolean return
- Armed guard rejecting signing changes in flight
- Fixes pre-existing NULL deref in the removed `get_instance_for_status()` (no null check before `inst->get_instance_id()`)
- Proper local variable naming (`_fd` → `fd`, `_instance_id` → `instance_id`)

See inline comments for specifics.

File: src/modules/mavlink/mavlink_sign_control.cpp [hunk 9]
```diff
@@ -44,6 +44,7 @@
 static mavlink_signing_streams_t global_mavlink_signing_streams = {};
 
 static const uint32_t unsigned_messages[] = {
+	MAVLINK_MSG_ID_HEARTBEAT,
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_sign_control.cpp:49]: Adding HEARTBEAT to the unsigned allowlist aligns with the MAVLink spec recommendation, but expands the attack surface: with signing active, an attacker can inject spoofed heartbeats to create phantom vehicles on the GCS or confuse companion computers doing system discovery.

Worth a brief code comment here explaining the rationale (spec compliance / interop requirement), since the security tradeoff isn't obvious from the code alone. The docs cover it well, but the code is where someone reviewing security will look first.

**Comment by mrpollo** [comment]
Thanks for the review @dakejahl I have updated the PR with your comments and suggestions

File: src/modules/mavlink/mavlink_main.h [hunk 10]
```diff
@@ -494,7 +492,9 @@ class Mavlink final : public ModuleParams
 
 	bool radio_status_critical() const { return _radio_status_critical; }
 
-	bool accept_unsigned(int32_t sign_mode, bool is_usb_uart, uint32_t message_id) { return _sign_control.accept_unsigned(sign_mode, is_usb_uart, message_id); }
+	bool accept_unsigned(uint32_t message_id) { return _sign_control.accept_unsigned(message_id); }
+	void set_signing_key_dirty() { _signing_key_dirty.store(true); }
+	void check_signing_key_dirty() { if (_signing_key_dirty.load()) { _signing_key_dirty.store(false); _sign_control.reload_key(); } }
```
Comment (dakejahl) [inline src/modules/mavlink/mavlink_main.h:497]: Nit: `exchange(false)` is more idiomatic and avoids the (harmless) TOCTOU between `load()` and `store(false)`:

```suggestion
	void check_signing_key_dirty() { if (_signing_key_dirty.exchange(false)) { _sign_control.reload_key(); } }
```

Not blocking — current code is correct since only the owning thread clears the flag.

**Review by dakejahl — DISMISSED** [review]
All three issues from the previous review have been addressed:

1. **`accept_unsigned_callback` now holds `mavlink_module_mutex`** ✓
2. **Cross-thread `reload_key()` race eliminated** — replaced with `px4::atomic_bool _signing_key_dirty` flag + self-reload on each instance's own receiver thread ✓
3. **Propagation loops use mutex and are deduplicated** — single `if (KEY_ACCEPTED || SIGNING_DISABLED)` block with `LockGuard` ✓
4. **HEARTBEAT allowlist has code comment explaining the tradeoff** ✓

The dirty-flag pattern is clean: `set_signing_key_dirty()` is safe to call from any thread (atomic store), and `check_signing_key_dirty()` in the receiver loop ensures each instance reloads on its own thread before the next `poll()`. The worst case for the load-then-store (vs `exchange`) is a harmless redundant reload.

One minor nit inline. LGTM otherwise.

**Review by dakejahl — COMMENTED** [review]
`accept_unsigned_callback` grabs `mavlink_module_mutex` on every unsigned message when signing is active. On a busy link with non-signing peers (SiK radios sending `RADIO_STATUS`, unsigned `HEARTBEAT`s, ADSB traffic), this is a mutex acquisition per message in the hot receive path.

`forward_message()` already does this (pre-existing), but there's no reason to add a second mutex grab when it's avoidable.

Since `_mavlink_signing.link_id` is set to `instance_id` in `start()` and never changes, the callback can index directly into the array — no loop, no lock:

```cpp
static bool accept_unsigned_callback(const mavlink_status_t *status, uint32_t message_id)
{
	if (status->signing) {
		Mavlink *inst = mavlink_module_instances[status->signing->link_id];

		if (inst != nullptr) {
			return inst->accept_unsigned(message_id);
		}
	}

	return false;
}
```

This is safe because the callback only fires on an instance's own receiver thread (from `mavlink_parse_char`), and the instance can't be destroyed while its receiver thread is running. The `link_id` is the instance's own index in the array.

**Comment by hamishwillee** [comment]
> It also restricted SETUP_SIGNING to USB only, which is narrower than the spec requires.

True, but that is not a reason to change it. 
[and by the same logic you would have to remove "Reject SETUP_SIGNING while armed" as that is not in the spec]

The spec allows for you to control "acceptance method" for the key any way you like. So you can allow it to change OTA, or you could have a thumbprint on the device which does biometrics and only allows updates on that channel.
The decision to allow over USB only ensures that someone can only make the change with physical access to the vehicle. That means that even if I somehow get the key taped to the underside of your computer, I can't take over the device unless I have it in hand.

I don't think that should be a requirement, but it is clearly a restriction that some people would appreciate. So consider adding it back as "Signing restricted to USB" for those who want it / parity with ArduPilot.

In the "how it works", just a few comments.

> Allow disabling signing via signed all-zero key

This is in the spec. It's good.

> Reject SETUP_SIGNING while armed

This is not in the spec but might make sense. FWIW it is kind of equivalent to having a USB connection, since before being armed you almost certainly have physical possession.

> Treat duplicate disable as no-op (QGC sends twice for reliability)

Again, not in spec, but this should be a Noop, since once disabled, disabling again is meaningless.

**Comment by hamishwillee** [comment]
PS I haven't looked at the docs, but  I am hoping you will add back the param and will do so then.

**Comment by mrpollo** [comment]
On `MAV_SIGN_CFG`: The old parameter controlled unsigned message acceptance policy per-link, not key provisioning. Adding it back means GCS implementations need to track and synchronize signing enforcement state across links, and handle edge cases when policies differ between links. If other flight stacks implement similar parameters with different policy semantics, GCS tools like QGC would need to handle each variant separately, increasing maintenance burden across the ecosystem. The current approach is simpler: signing is either active (key on SD) or not, and enforcement is the same on all links.

On USB unsigned access: I understand the appeal as a recovery mechanism for lost keys. Without it, the only recovery is physically removing the SD card and deleting the key file. That said, allowing unsigned messages on USB introduces a forwarding problem. `_mavlink_resend_uart` copies raw bytes without re-signing. Any unsigned message accepted on USB gets forwarded as-is to signed telemetry links. Every device listening on those links would receive unsigned messages mixed in with signed ones and would have to decide whether to trust them.

If there's demand for a USB unsigned escape hatch in the future, it should come alongside a valid use case and changes to the forwarding path to prevent unsigned messages from leaking onto signed links.

**Comment by hamishwillee** [comment]
Thanks for the explanation. Will look at the docs on Weds.

**Review by hamishwillee — APPROVED** [review]
@mrpollo I've given the docs a relatively minor subedit, mostly for readability/structure. Look good.

One thing we might stress even more is that you should provision over USB (i.e. we do mention that you should provision over a secure link, but we perhaps need to put this in the security considerations section of hardening. I'll leave that to you, but this is good from a docs persepective.

**Review by dakejahl — APPROVED** [review]
