### PR TITLE
fix(uxrce_dds_client): fix session reconnection after agent restart

### LINKED ISSUE #26022: [Bug] [micro-ROS] PX4 1.16 uxrce_dds_client does not reconnect after XRCE-DDS Agent restart (requires FC reboot
### Describe the bug

Environment

PX4 Firmware: 1.16.x

Board:  Pixhawk

Transport: micro-ROS (UXRCE-DDS) over serial

Companion Computer: NVIDIA Jetson (Ubuntu)

XRCE-DDS Agent: Micro XRCE-DDS Agent v2.4.x from eProsima (compiled from source)

Startup method: systemd unit on Jetson with Restart=on-failure

Baud: 921600

**Summary**

uxrce_dds_client successfully connects to the XRCE-DDS Agent on first boot, and ROS 2 topics from PX4 appear normally.

However, if the XRCE-DDS Agent is restarted or crashes, PX4 never reconnects.
uxrce_dds_client status remains “Running, disconnected” indefinitely.

The only way to restore communication is to hard reset the flight controller.

### To Reproduce

**Start PX4 with:**
 uxrce_dds_client start -t serial -d /dev/ttyS2 -b 921600
**Start XRCE-DDS Agent on Jetson:**
MicroXRCEAgent serial --dev /dev/ttyUSB0 -b 921600 -m dds -v4
**Verify ROS 2 topics appear on Jetson:**
ros2 topic list
**Now restart the agent:**
**Either via systemd:**
sudo systemctl kill -s SIGKILL xrce-dds-agent.service

Or manually kill the process.
Agent restarts correctly and reopens /dev/ttyUSB0.
PX4 continues to show:

Running, disconnected

and never reconnects.

### Expected behavior

PX4 micro-ROS client (uxrce_dds_client) should automatically re-establish the XRCE session when the agent comes back.

Actual Behavior

Agent restarts and listens correctly.

PX4 stays “Running, disconnected”.

No DDS handshake occurs.

No ROS 2 topics from PX4.

Only a hard reset of the flight controller restores connectivity.

**Questions for PX4 team**

Is reconnection supposed to work on PX4 1.16?

Is this a known issue with uxrce_dds_client session recovery?

Is there a param or recommended workaround to force reconnection without rebooting?

Should the client automatically restart the XRCE session when the Agent returns?

### Screenshot / Media

jetson@jetson-desktop:~$ systemctl status xrce-dds-agent.service
● xrce-dds-agent.service - Micro XRCE-DDS Agent for Flight Controller
     Loaded: loaded (/etc/systemd/system/xrce-dds-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2025-12-01 17:54:11 PKT; 9s ago
    Process: 12448 ExecStartPre=/bin/sh -c if [ -e "$XRCE_DEV" ]; then /usr/bin/fuser -k "$XRCE_DEV" || true; fi (code=exited, status=0/SUCCESS)
    Process: 12450 ExecStartPre=/bin/sh -c if [ -e "$XRCE_DEV" ]; then /bin/stty -F "$XRCE_DEV" "$XRCE_BAUD" cs8 -cstopb -parenb -ixon -ixoff -crtscts || true; fi (code=exited, status=0/SUC>
   Main PID: 12452 (MicroXRCEAgent)
      Tasks: 7 (limit: 18452)
     Memory: 4.0M
        CPU: 86ms
     CGroup: /system.slice/xrce-dds-agent.service
             └─12452 /usr/local/bin/MicroXRCEAgent serial --dev /dev/ttyUSB0 -b 921600 -m dds -v4

Dec 01 17:54:11 jetson-desktop systemd[1]: Starting Micro XRCE-DDS Agent for Flight Controller...
Dec 01 17:54:11 jetson-desktop systemd[1]: Started Micro XRCE-DDS Agent for Flight Controller.
Dec 01 17:54:11 jetson-desktop MicroXRCEAgent[12452]: [1764593651.284952] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
Dec 01 17:54:11 jetson-desktop MicroXRCEAgent[12452]: [1764593651.285686] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4

### Flight Log

_No response_

### Software Version

_No response_

### Flight controller

_No response_

### Vehicle type

None

### How are the different components wired up (including port information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PavelGuzenfeld**
## Summary

Fixes #26022

When the Micro XRCE-DDS Agent is restarted (e.g. via systemd or Docker), the PX4 client stays "Running, disconnected" forever and never re-establishes the session. Three bugs prevented reconnection:

### Bug 1: `session.on_pong_flag` never reset (root cause)

After the first successful pong response, `on_pong_flag` was set to 1 by the XRCE library but **never reset to 0** by the client code. This caused `checkConnectivity()` to always see `_had_ping_reply = true`, masking the fact that the agent was gone. The 3-missed-pings disconnection condition could never trigger.

**Fix:** Reset `session.on_pong_flag = 0` after reading it.

### Bug 2: `_subs->reset()` never called on teardown

When a session was deleted for reconnection, `SendTopicsSubs::reset()` was never called. Stale uORB file descriptors from the previous session persisted, causing the next session's publishers to malfunction.

**Fix:** Call `_subs->reset()` in `deleteSession()`.

### Bug 3: `_connected` not reset in `deleteSession()`

While the outer loop already exits when `_connected` becomes false, explicitly resetting it in `deleteSession()` ensures clean state regardless of the call path.

## Test plan

All verified in Docker (`px4io/px4-dev:v1.17.0-beta1`):

- [x] `make px4_sitl_default` — SITL build passes
- [x] `make px4_fmu-v6x_default` — NuttX build passes (1253/1253)
- [x] `make tests` — 154/154 pass
- [x] `check_code_style_all.sh` — format checks passed

### SITL reconnection scenario (verified in Docker)

```
=== Test 1: Start agent, verify connection ===
  PASS: Client connected to agent
    INFO  [uxrce_dds_client] synchronized with time offset 1774156926591857us
    INFO  [uxrce_dds_client] successfully created rt/fmu/out/register_ext_component_reply_v1 data writer, topic id: 212

=== Test 2: Kill agent, verify disconnect detection ===
  PASS: Disconnect detected
    ERROR [uxrce_dds_client] No ping response, disconnecting
    INFO  [uxrce_dds_client] session disconnected, attempting to reconnect...

=== Test 3: Verify reconnect attempt message ===
  PASS: Reconnect attempt logged

=== Test 4: Restart agent, verify reconnection ===
  PASS: Client reconnected to new agent
    INFO  [uxrce_dds_client] synchronized with time offset 1774156926944585us
    INFO  [uxrce_dds_client] successfully created rt/fmu/out/register_ext_component_reply_v1 data writer, topic id: 212
    INFO  [uxrce_dds_client] successfully created rt/fmu/out/battery_status_v1 data writer, topic id: 20

Results: 4 passed, 0 failed
```

### CODE REVIEW

**Comment by sansha** [comment]
Hey, just wanted to chime in - just tested this and can confirm it works! 
Thank you for tackling this, this was also a challenge for me.
I can also support with testing or else if helpful, would be great to get this into the next release!

**Comment by PavelGuzenfeld** [comment]
> Hey, just wanted to chime in - just tested this and can confirm it works! Thank you for tackling this, this was also a challenge for me. I can also support with testing or else if helpful, would be great to get this into the next release!

Thank you, @sansha! I'd love to collaborate. If you need anything at all, I'm ready to chip in.

**Comment by sansha** [comment]
Hey, while testing this PR worked for me, I found a bug when cherry-picking it to 1.16 (which we are curerntly using)

Full transparency: This description was AI generated but the bug indeed existed and this fix resolved it for me. @dakejahl does this sound like a potential bug?

### Bug in `SendTopicsSubs::reset()` breaks reconnection on hardware when cherry-picked to `1.16.1`

We cherry-picked this PR onto v1.16.1 and tested on a Pixhawk 6X with a serial XRCE-DDS agent. The disconnect detection and session teardown work correctly, but **reconnection enters an infinite loop**:

```
INFO  [uxrce_dds_client] successfully created rt/fmu/out/home_position data writer, topic id: 123
ERROR [uxrce_dds_client] Payload TX rate zero for too long, disconnecting
INFO  [uxrce_dds_client] session disconnected, attempting to reconnect...
INFO  [uxrce_dds_client] init serial /dev/ttyS4 @ 921600 baud
INFO  [uxrce_dds_client] synchronized with time offset ...
INFO  [uxrce_dds_client] successfully created rt/fmu/out/... (all writers)
ERROR [uxrce_dds_client] Payload TX rate zero for too long, disconnecting
(repeats forever)
```

ROS 2 topics appear but nothing is published. The session connects, writers are created, but no data ever flows.

### Root cause

The bug is in `dds_topics.h.em` — `SendTopicsSubs::reset()` doesn't clear `fds[].events`:

```cpp
void SendTopicsSubs::reset() {
    num_payload_sent = 0;
    for (unsigned idx = 0; idx < ...; ++idx) {
        send_subscriptions[idx].data_writer = uxr_object_id(0, UXR_INVALID_ID);
        orb_unsubscribe(fds[idx].fd);
        fds[idx].fd = -1;
        // BUG: fds[idx].events still == POLLIN from first init()
    }
};
```

On reconnect, `init()` checks `if (fds[idx].events == 0)` before calling `orb_subscribe()`. Since `events` was never cleared, the guard evaluates false, `orb_subscribe()` is skipped, and all fds remain at -1. `px4_poll()` on invalid fds returns 0, `update()` is never called, TX rate stays zero → disconnect after `UXRCE_DDS_TX_TO` seconds.

### Fix

One line in `reset()`:

```cpp
fds[idx].fd = -1;
fds[idx].events = 0;  // allow init() to re-subscribe on reconnect
```

This isn't caught in SITL because SITL reconnection tests typically kill/restart the agent quickly enough that the timing works out differently. On real hardware with a serial transport the failure is 100% reproducible.

Note: #26161 also modifies `dds_topics.h.em` but doesn't fix this either.

Our fork with the complete fix (this PR + the `reset()` fix): [Nomadic-Drones/PX4-Autopilot@v1.16.1-nomadic](https://github.com/Nomadic-Drones/PX4-Autopilot/tree/v1.16.1-nomadic) — specifically commit [`398c581`](https://github.com/Nomadic-Drones/PX4-Autopilot/commit/398c5815e0).

**Comment by PavelGuzenfeld** [comment]
@sansha thanks, good catch — pushed the fix in 47ec271.

File: src/modules/uxrce_dds_client/dds_topics.h.em [hunk 1]
```diff
@@ -120,6 +120,7 @@ void SendTopicsSubs::reset() {
 		send_subscriptions[idx].data_writer = uxr_object_id(0, UXR_INVALID_ID);
 		orb_unsubscribe(fds[idx].fd);
 		fds[idx].fd = -1;
+		fds[idx].events = 0;
```
Comment (mrpollo) [inline src/modules/uxrce_dds_client/dds_topics.h.em]: might be worth adding a comment here to explain why we need this

**Comment by sansha** [comment]
@dakejahl thank you for the review! 
@PavelGuzenfeld what is missing to get this merged? Thanks!

**Comment by PavelGuzenfeld** [comment]
> @dakejahl thank you for the review! @PavelGuzenfeld what is missing to get this merged? Thanks!

By me, its ready. CI passed and reviews approved.

**Comment by PavelGuzenfeld** [comment]
> Is the publication side unaffected by reconnections?

Yes. Tested locally: kill agent, restart, all 27 DataWriters recreated cleanly, no reconnect loop. Publication side goes through the same `reset()` → `init()` path as subscriptions. With the fix, data flows again after reconnect.

File: src/modules/uxrce_dds_client/dds_topics.h.em (hunk 1 above)
Comment (PavelGuzenfeld) [reply src/modules/uxrce_dds_client/dds_topics.h.em]: done.
