### PR TITLE
sim: refactor startup scripts and fix gz sim standalone 

### LINKED ISSUE #24598: [Bug] px4-rc.simulator set gc_command in wrong place
### Describe the bug

I just want to boot px4 by `PX4_GZ_STANDALONE=1 make px4_sitl gz_x500`, and I run the script in https://github.com/PX4/PX4-gazebo-models/blob/main/simulation-gazebo to start the model, and in theory, px4 will connect to the gazebo and stop waiting for gazebo world. But it won't, and reach the limit retry times, then exit.

### To Reproduce

1. Just build px4 normally, `make px4_sitl gz_x500`
2. Install the script in https://github.com/PX4/PX4-gazebo-models/blob/main/simulation-gazebo
3. Uncomment the line `set +x` in rcS to see the debug info.
4. Run `PX4_GZ_STANDALONE=1 make px4_sitl gz_x500` in a terminal, then run script installed at step 2 in a different terminal.
5. Well, after 30 retries, px4 will exit. You can see `gz_command` is set to NULL because it is only set in the branch of `if [ -z "${PX4_GZ_STANDALONE}" ]; then`.

### Expected behavior

px4 should connect to the gazebo simulator after the script [simulation-gazebo](https://github.com/PX4/PX4-gazebo-models/blob/main/simulation-gazebo) run.

### Screenshot / Media

Image

### Flight Log

No log here

### Software Version

checkout at commit e0d15b7a80. QGC version v4.4.3，`simulation-gazebo` script checkout commit c3905a7, url https://github.com/PX4/PX4-gazebo-models/blob/main/simulation-gazebo

$ gz sim --version
Gazebo Sim, version 8.9.0
Copyright (C) 2018 Open Source Robotics Foundation.
Released under the Apache 2.0 License.

### Flight controller

_No response_

### Vehicle type

None

### How are the different components wired up (including port information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dakejahl**
fixes #24598
- refactor px4-rc.simulator into sim specific startup scripts
- fix gz sim launch for PX4_GZ_STANDALONE
- fix gz sim `simulation-gazebo` script by adding the **server.config** file to the models repo
- removed px4-rc.params since it was unused 

Long term we need to have all gz sim stuff in the submodule, with the exception of the gz_bridge

### CODE REVIEW

**Review by AlexKlimaj — APPROVED** [review]

File: ROMFS/px4fmu_common/init.d-posix/px4-rc.jmavsim [hunk 1]
```diff
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck disable=SC2154
```
Comment (dagar) [inline ROMFS/px4fmu_common/init.d-posix/px4-rc.jmavsim:2]: Why?

Comment (dakejahl) [reply ROMFS/px4fmu_common/init.d-posix/px4-rc.jmavsim:2]: CI fails without it, carried over from here
https://github.com/PX4/PX4-Autopilot/pull/24600/files#diff-0d4c77fd4a6b4056f7689aa9e02d5d52525f4a0e6108bc32cbd8b8b880bcccfdL2

**Comment by bastianhjaeger** [comment]
@dakejahl We where using `px4-rc.params`. Any quick suggestions for an alternative?

**Comment by dakejahl** [comment]
@bastianhjaeger what were you using it for? I removed it here because nothing in-tree used the file and it's intended usage wasn't clear. Looks like sitl doesn't have the an extras/board_defaults, maybe we need to add something? I suppose also it should be a filepath from an environment variable (check if env var is set, check that filepath exists, load file)

**Comment by bastianhjaeger** [comment]
In our case we where overriding the UXRCE DDS config for all verhicles to use custom participant config. Now it needs to be done vehicle per vehicle for real and simulated vehicles, as far as I see.

**Comment by dakejahl** [comment]
We used to have an rc.extras that served this general purpose, not sure what happened to it. But it sounds like you need it back.

**Comment by bastianhjaeger** [comment]
Agreed. I would vote for reverting that section. Shall I open a new PR, probably?

**Comment by dakejahl** [comment]
Yeah open a PR!
