### PR TITLE
params: COM_RC_LOSS_T: clarify safe adjustment of RC loss timeout

### LINKED ISSUE #25045: [Bug] False positive RC failsafe triggered when COM_RC_LOSS_T is less than the manual_control_setpoint update time interval
### Describe the bug

When the parameter COM_RC_LOSS_T (definition can be found in the [PX4 Parameter Reference documentation](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#COM_RC_LOSS_T))) is set to a value less than the actual update interval of manual_control_setpoint, the vehicle immediately enters RC failsafe mode.

Potential Issue:
On resource-constrained hardware, various factors can cause the publication and subscription period of manual_control_setpoint to be extended. In such scenarios, a COM_RC_LOSS_T value that is too small could lead to the inability to control the flight controller via RC.
Example:
The Joystick in QGC was opened, and the flight controller successfully took off. After takeoff, the parameter COM_RC_LOSS_T was set to 0.1. After a while, the drone entered RC loss failsafe mode, during which no other operations were performed (See [Log](https://logs.px4.io/plot_app?log=0aadb8d9-c4d6-42e1-aaed-af943c701398)).

Image

Corresponding code:
https://github.com/PX4/PX4-Autopilot/blob/64989c3b8d062561523a71a68a999b446e50a91e/src/modules/commander/HealthAndArmingChecks/checks/rcAndDataLinkCheck.cpp#L49-L50

### To Reproduce
Case 1:
1. QGC enable joystick;
2. `commander takeoff`;
3.  run `uorb top` command to check that the update cycle for the manual_control_setpoint message is 25 Hz;
4. `param set COM_RC_LOSS_T 0.039` (Set a value less than 0.04);
5. Drone triggers RC failsafe and can't use RC to control drone.

Case2:
1. QGC enable joystick;
2. `commander takeoff`;
3. `param set COM_RC_LOSS_T 0.1`;
4. After waiting for a moment, the drone may enter failsafe mode.

### Expected behavior

_No response_

### Screenshot / Media

_No response_

### Flight Log

[Log](https://logs.px4.io/plot_app?log=0aadb8d9-c4d6-42e1-aaed-af943c701398)

### Software Version

PX4-v1.15.2

I've observed that later versions may also have this problem.

### Flight controller

sitl

### Vehicle type

Multicopter

### How are the different components wired up (including port information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lqs66**
Modified the description of the parameter COM_RC_LOSS_T to explicitly state that the timeout should not be set below the hardware capability. Otherwise, on limited hardware, a too low COM_RC_LOSS_T value may be smaller than the actual manual_control_setpoint update interval, thus triggering incorrect RC loss failsafe.

Fixes #25045

### CODE REVIEW

File: src/modules/commander/commander_params.c [hunk 1]
```diff
@@ -127,6 +127,7 @@ PARAM_DEFINE_INT32(COM_HLDL_REG_T, 0);
  *
  * The time in seconds without a new setpoint from RC or Joystick, after which the connection is considered lost.
  * This must be kept short as the vehicle will use the last supplied setpoint until the timeout triggers.
+ * **Note:** Setting this value too low may trigger an incorrect RC failsafe. This value can be longer on resource-constrained hardware or under high system load. It is recommended to carefully test and adjust this value based on the specific hardware performance.
```
Comment (dakejahl) [inline src/modules/commander/commander_params.c]:
```suggestion
 * Ensure the value is not set lower than the update interval of the RC or Joystick.
```

Comment (dakejahl) [reply src/modules/commander/commander_params.c]: I shortened the text to reduce verbosity while conveying the point

**Review by dakejahl — APPROVED** [review]
