### PR TITLE
Fix differential thrust for Tailsitter in FW mode

### LINKED ISSUE #12302: Differential thrust in Tailsitter is link to aileron not rudder
**Describe the bug**
In new firmware there is a new parameter for VTOL aircraft "VT_FW_DIFTHR_EN" used to enable Differential thrust in forwards flight. But I'm a Quad x Tailsitter , when I enable this, the motors not responded to my  yaw control but link to my roll control. I think maybe this is because tailsitter's axis of fixedwing is different from multicoptor. maybe we can try if it can reproduce in a Dual tailsitter 

**To Reproduce**
1. flash firmware Px4 1.9.0 (Git revision ea48cd4970000000) 
2. set parameter "VT_FW_DIFTHR_EN" to 1 ; "VT_FW_DIFTHR_SC" to 0.5
3. armed in FW mode and turn yaw stick there is no response on all motor
4. armed in FW mode and turn roll stick there is Differential thrust response

**Expected behavior**
armed in FW mode and turn yaw stick there is Differential thrust response

**Log Files and Screenshots**
put here later

### PR DESCRIPTION
**Pull request by RicardoM17**
Replaces #12518 

Closes #12302

Followed the same logic and just updated the PR with a quick test in SITL.

Log: https://logs.px4.io/plot_app?log=fb7ebb3e-53ac-4c8a-baa7-548dc4a8ede0

@sfuhrer If you could have a look, and perhaps @xdwgood can you test this in a tailsitter as well?

@dagar FYI

### CODE REVIEW

**Comment by xdwgood** [comment]
I have some concerns. The pr has only been tested on a four-motor taisitter, whether this modification works on a two-motor tailsitter.
At present, for the tailsitter with two motors, the heading change in the fixed-wing mode is done through the aileron. I know this works fine in the lioter state in fw mode.　So I have a question: why do we need to introduce the current pr?（At present, the heading control can be completed without the motor differential speed）On the other hand, once the motor differential is used to change the heading, does this affect the pitch and roll control in the fw mode?

File: src/modules/vtol_att_control/tailsitter.cpp [hunk 1]
```diff
@@ -293,6 +288,11 @@ void Tailsitter::fill_actuator_outputs()
 	if (_vtol_schedule.flight_mode == vtol_mode::FW_MODE) {
 		mc_out[actuator_controls_s::INDEX_THROTTLE] = fw_in[actuator_controls_s::INDEX_THROTTLE];
 
+		/* allow differential thrust if enabled */
+		if (_params->diff_thrust == 1) {
```
Comment (xdwgood) [inline src/modules/vtol_att_control/tailsitter.cpp:292]: I suggest moving this change to the top to keep it clean (only responsible for determining the throttle)

```
if (_vtol_schedule.flight_mode == vtol_mode::FW_MODE && _params->diff_thrust == 1)) {
mc_out[actuator_controls_s::INDEX_ROLL] = fw_in[actuator_controls_s::INDEX_YAW] * _params->diff_thrust_scale;
} else {
mc_out[actuator_controls_s::INDEX_ROLL]  = mc_in[actuator_controls_s::INDEX_ROLL]  * _mc_roll_weight;
}
```

Comment (xdwgood) [reply src/modules/vtol_att_control/tailsitter.cpp:292]: For tailsitter users, when should I enable this parameter and when should I disable it?

**Comment by sfuhrer** [comment]
> I have some concerns. The pr has only been tested on a four-motor taisitter, whether this modification works on a two-motor tailsitter.

It shouldn't matter if dual or quad tailsitter. Both benefit form having yaw control in FW, and the correct allocation is then done in the corresponding mixer. 

> At present, for the tailsitter with two motors, the heading change in the fixed-wing mode is done through the elevon. I know this works fine in the lioter state in fw mode.　So I have a question: why do we need to introduce the current pr?（At present, the heading control can be completed without the motor differential speed）On the other hand, once the motor differential is used to change the heading, does this affect the pitch and roll control in the fw mode?

Yes you can have directional control of a fixed-wing aircraft without controlling the yaw axis actively on most frames, but for a nicely coordinated turns or aggressive manual maneuvers yaw control is still beneficial.

File: src/modules/vtol_att_control/tailsitter.cpp (hunk 1 above)
Comment (sfuhrer) [reply src/modules/vtol_att_control/tailsitter.cpp:292]: I don't have a strong opinion for one or the other way, both work.

Comment (sfuhrer) [reply src/modules/vtol_att_control/tailsitter.cpp:292]: >For tailsitter users, when should I enable this parameter and when should I disable it?

You should enable it when your vehicle has bad passive yaw stability or you want to fly aggressive maneuvers.

**Review by sfuhrer — APPROVED** [review]
Looks good to me, also tested it quickly in SITL.

**Comment by aoberai** [comment]
Does this allow for controlling a quadrotor tailsitter that does not have elevons like the Swan K1? I heard that PX4 doesn't currently have differential thrust for pitch and roll in cruise.

**Comment by sfuhrer** [comment]
> Does this allow for controlling a quadrotor tailsitter that does not have elevons like the Swan K1? I heard that PX4 doesn't currently have differential thrust for pitch and roll in cruise.

No that is not supported out of the box yet, but would be fairly straight forward to enable with some code changes if you want to play with it. We played around with it recently: https://github.com/PX4/PX4-Autopilot/commits/quad-tailsitter-no-surfaces-testing
